version: '3'
services:
  db:
    image: mysql
    container_name: mysql_anime_listor
    environment:
    
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3307:3306'
    volumes:
      - witortests:/var/lib/mysql

volumes:
  witortests: